### ISSUE TITLE
Downloads

### ISSUE THREAD

**Issue by robson-koji** [rajatdiptabiswas/flask-api-hugging-face-fb-bart-large-mnli#1]
Hi Rajat, 

What are all of those downloads when starting flask server:

flask run --host=0.0.0.0
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
Downloading: 100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.15k/1.15k [00:00<00:00, 542kB/s]
Downloading:   2%|██▍                                                                                                               | 34.4M/1.63G [00:04<03:46, 7.03MB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.63G/1.63G [02:43<00:00, 9.99MB/s]
Downloading: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 26.0/26.0 [00:00<00:00, 13.4kB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 899k/899k [00:01<00:00, 752kB/s]
Downloading: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 456k/456k [00:00<00:00, 526kB/s]
Downloading: 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1.36M/1.36M [00:01<00:00, 1.29MB/s]
 * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
 * Running on http://192.168.0.44:5000/ (Press CTRL+C to quit)

**Comment by rajatdiptabiswas** [comment]
Hi @robson-koji,

The flask application needs to download the BART model from Hugging Face and its prerequisites.
I guess that's what you're seeing here.

Cheers.

**Comment by robson-koji** [comment]
I got it! I am just digging into Hugging Face architecture. I am looking for something to make zero-shot predictions. 

Your package is a very good starting point. 

Thank you !
